learn-rails/config/routes.rb
Rails.application.routes.draw do

  root 'clients#index'

  resources :clients do
    get '/top_five_people' => 'clients#top_five_people'
    get '/invoices/amount_per_year' => 'invoices#amount_per_year'
    get '/invoices/cont_per_month' => 'invoices#cont_per_month'
    get 'invoices/all' => 'invoices#all'
    resources :invoices, only: [:index, :new, :create, :show, :amount_per_year]
  end
  resources :people
  resources :invoices, only: [:edit, :update, :destroy]
  resources :contacts

end

learn-rails/app/models/client.rb
class Client < ActiveRecord::Base

  # as_enum :type_document, [dni: 0, ci: 1, ld: 2, ld: 3], prefix: true
  as_enum :type_document, %i{dni, ci, ld }, prefix: true

  has_many :invoices, dependent: :restrict_with_error
  has_many :people, through: :invoices
  has_many :contacts, inverse_of: :client
  accepts_nested_attributes_for :contacts, allow_destroy: true



  def invoiced_more_people()
    self.people.group("name").order("sum_amount DESC").sum("amount").first(5)
  end

  validates :contacts,
    presence: true

  validates :firstname,
    presence: true,
    length: { in: 2..20 }
  validates :lastname,
    presence: true,
    length: { in: 2..20 }
  #No sea menor de edad
  validates :born,
    presence: true,
    date: {
      before: Proc.new { Time.now - 18.year }, message: "Debe tener mayoría de edad (18)."
    }
  validates :type_document_cd,
    presence: true,
    inclusion: { in: %w(DNI CI LD), message: "clave: %{value} no es valido" }
  validates :number_document, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 800000,
    less_than_or_equal_to: 99999999},
    uniqueness: {scope: :type_document_cd},
    presence: true
  # validates :phone,
  #   presence: false,
  #   format: { with: /\A(\+?[0-9]{2}[ .-]?[0-9]{3,4}[ .-]?[0-9]{7}[0-9]?){0,1}\Z/ }
  validates :code,
    format: { with: /\A[0-9]{2}-[0-9]{8}-[0-9]\Z/ },
    presence: true,
    uniqueness: true


end

learn-rails/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create

    @client = Client.new(client_params)

    if @client.save
      redirect_to @client
    else
      render 'new'
    end
  end

  def show
    @client = Client.find(params[:id])
    @contacts = @client.contacts
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)

      redirect_to @client
    else
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    if @client.destroy
      msg = "El cliente ha sido eliminada."
    else
      msg = "No se pueden eliminar clientes con facturas asociadas."
    end

    redirect_to clients_path, notice: msg
  end

  def top_five_people()
    @client = Client.find(params[:client_id])
    @people = Client.find(params[:client_id]).invoiced_more_people()

  end

  private

  def client_params
    params
      .require(:client)
      .permit(
        :firstname, :lastname, :born,
        :type_document_cd, :number_document, :code,
        contacts_attributes: [:id, :contact, :contact_type_id, :_destroy])
  end

end

learn-rails/app/helpers/client_helper.rb
module ClientHelper
require 'date'

  def age (d)
    if d
      today = Date.today
      a = today.year - d.year
      a = a - 1 unless ( today.month > d.month or
          (today.month >= d.month and today.day > d.day) )
      a
    else
      "No se pudo realizar la operacion"
    end
  end

end

learn-rails/app/views/clients/_form.html.erb
<%= nested_form_for (@client) do |f| %>
  <% if @client.errors.any? %>
  <div class="container container-fluid">
    <div id="error_explanation">
      <h3> Encontramos <%= pluralize(@client.errors.count, "error") %>/es en el formulario:</h3>
      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  <fieldset>
    <h3><legend class="text-center"> <%= @title %> </h3></legend>

    <div class="form-group">
        <%= f.label :nombre, class: "col-md-4 control-label"  %>
        <%= f.text_field :firstname, :required => true, class: "form-control", min: "2", max: "20"  %>
    </div>

    <div class="form-group">
      <%= f.label :apellido, class: "col-md-4 control-label" %>
      <%= f.text_field :lastname, :required => true, class: "form-control", min: "2", max: "20"  %>
    </div>

    <div class="form-group">
      <%= f.label :'Fecha de nacimiento', class: "col-md-4 control-label" %>
      <%= f.date_field :born, max: Date.today, min: Date.new(1900, 01, 01), :required => true, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :"Tipo De Documento", class: "col-md-4 control-label" %>
      <%= f.select(:type_document_cd, [['DNI', 'DNI'], ['CI', 'CI'], ['LD', 'LD']], class:"form-control" ) %>
    </div>

    <div class="form-group">
      <%= f.label :Documento, class: "col-md-4 control-label" %>
        <%= f.number_field :number_document, min: "800000", max: "99999999", :required => true, class: "form-control", placeholder: "12345678"  %>
    </div>

    <hr>

    <p><%= f.link_to_add "Agregar contacto", :contacts, :class => 'btn btn-sm btn-success', :data => { :target => "#contacts" } %></p>
    <table class="table" id="contacts">
      <%= f.fields_for :contacts, :wrapper => false do |ct| %>
        <tr class="fields">
          <td><%= ct.select(:contact_type_id, ContactType.all.collect {|c| [c.name_cd, c.id] }, class:"form-control", as: :select ) %></td>
          <td><%= ct.text_field :contact, class: "form-control" %></td>
          <td><%= ct.link_to_remove "Quitar contacto" %></td>
        </tr>
      <% end %>
    </table>

    <hr>
<!--
    <div class="form-group">
      <label class="col-md-4 control-label" for="client_Correo electronico">Correo electronico</label>
      <input class="form-control" required="required" placeholder="ejemplo@ejemplo.com" type="email" name="client[email]" id="client_email" />
    </div>

    <div class="form-group">
      <label class="col-md-4 control-label" for="client_Teléfono">Teléfono</label>
      <input class="form-control" placeholder="Ej.+54-0221-42345678" type="tel" name="client[phone]" id="client_phone" />
    </div>

    <div class="form-group">
      <label class="col-md-4 control-label" for="client_Móvil">Teléfono Móvil</label>
      <input class="form-control" required="required" placeholder="Ej. +54 0221 4234567" type="tel" name="client[mobile]" id="client_mobile" />
    </div>

    <div class="form-group">
      <label class="col-md-4 control-label" for="client_Direción">Direción</label>
      <input class="form-control" min="2" max="40" required="required" placeholder="Ej. Avenido 32 n.1280" type="text" name="client[address]" id="client_address" />
    </div> -->

    <div class="form-group">
      <%= f.label :"CUIL/CUIT", class: "col-md-4 control-label" %>
      <%= f.text_field :code, class: "form-control", :required => true, placeholder: "Ej. 20-28564123-9"  %>
    </div>

    <div class="form-group pull-right">
        <%= link_to "Cancelar", clients_path, class:"btn btn-danger", :required => true %>
        <%= f.submit class:"btn btn-primary", value: "Guardar"%>
    </div>
  </fieldset>
<% end %>

learn-rails/app/views/clients/_menu.html.erb
<aside class="sidebar col-sm-3">
  <ul>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

        <div class="panel-heading" role="tab" id="headingList">
          <div class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseList" aria-expanded="false" aria-controls="collapseList">
              Listados
            </a>
          </div>
        </div>
        <div id="collapseList" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingList">
          <div class="panel-body">
            <ul class="nav nav-pills nav-stacked">
              <li><%= link_to 'Lista de clientes', clients_path %></li>
              <li><%= link_to 'Lista de personas', people_path %>
            </ul>
          </div>
        </div>

      <div class="panel-heading" role="tab" id="headingOne">
        <div class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseAlumnos" aria-expanded="false" aria-controls="collapseAlumnos">
            Datos copados
          </a>
        </div>
      </div>
      <div id="collapseAlumnos" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
          <ul class="nav nav-pills nav-stacked">
          <li><a href="">Listado de facturas</a></li>
          <li><a href="">Monto total por año</a></li>
          <li><a href="">Top 5 de personas</a></li>
          </ul>
        </div>
      </div>

    </div> <!-- #accordion -->
  </ul>
</aside>

learn-rails/app/views/clients/edit.html.erb
<div class="panel panel-default">
	<div class="panel-body">

		<div class="hidden">
			<%= @title = "Editar datos" %>
		</div>
		<%= render 'form' %>

  </div>
</div>

learn-rails/app/views/clients/index.html.erb
<%= render template: 'notice' %>
<table class="table table-hover table-bordered table-condensed text-center">
	<div class="container-fluid">
		<div class="pull-left">
			<h2 class="text-center remove-margin">Listado de Clientes</h2>
		</div>
		<div class="pull-right">
				<%= link_to 'Crear cliente', new_client_path, class:"btn btn-default" %>
		</div>
	</div>
  <hr>
  <thead>
    <tr>
			<th class="text-center">Nombre y apellido</th>
			<th class="text-center">Documento</th>
			<th class="text-center">CIUL/CUIT</th>
      <th class="text-center">Edad</th>
			<th class="text-center">Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |cl| %>
      <tr>
        <td><%= cl.firstname %> <%= cl.lastname %></td>
				<td><%= cl.type_document_cd %> <%= cl.number_document %></td>
				<td><%= cl.code %></td>
        <td><%= age(cl.born) %></td>
				<td><%= link_to 'Ver', client_path(cl), class:"btn btn-sm btn-info" %>
				<%= link_to 'Editar', edit_client_path(cl), class:"btn btn-sm btn-info" %>
				<%= link_to 'Eliminar', client_path(cl), class:"btn btn-sm btn-danger",
                    method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

learn-rails/app/views/clients/new.html.erb
<div class="panel panel-default">
	<div class="panel-body">

		<div class="hidden">
			<%= @title = "Crear cliente" %>
		</div>
		<%= render 'form' %>

	</div>
</div>

learn-rails/app/views/clients/show.html.erb
<div class="col-md-9 col-md-offset-0">
<div class="panel panel-default">
	<div class="panel-body">

		<div class="text-center" >
		  <h3><legend class="text-center"> Informaci&oacute;n de cliente </h3></legend>

			<%= render template: "notice" %>

		  <h5>
		    <strong>Nombre:</strong>
		    <%= @client.firstname %>
		  </h5>

		  <h5>
		    <strong>Apellido:</strong>
		    <%= @client.lastname %>
		  </h5>

		  <h5>
		    <strong>Fecha de nacimiento</strong>
		    <%= @client.born.strftime "%d-%m-%Y" %>
		  </h5>

			<h5>
		    <strong>Tipo y n&uacute;mero de Documento:</strong>
		    <%= @client.type_document_cd.upcase %> <%= @client.number_document %>
		  </h5>

			<!-- Ver si tiene contactos, de momento, queda asi -->
			<% @contacts.each do |ct| %>
				<h5>
					<strong><%= ct.name_type.capitalize %></strong>
					<%= ct.contact %>
				</h5>
			<% end %>

		  <h5>
		    <strong>N&uacute;mero de CUIL/CUIT:</strong>
		    <%= @client.code %>
		  </h5>
		</div>
  </div>
</div>

<div class="pull-left">
	<%= link_to 'Agregar factura', new_client_invoice_path(@client), class: "btn btn-sm btn-info"  %>
  <%= link_to 'Editar', edit_client_path(@client), class: "btn btn-sm btn-info"  %>
	<%= link_to 'Eliminar', client_path(@client), class:"btn btn-sm btn-danger",
							method: :delete, data: { confirm: '¿Estás seguro?' } %>
</div>
<div class="pull-right">
	<%= link_to 'Volver', :back, class: "btn btn-sm btn-default" %>
</div>
</div>

learn-rails/app/views/clients/top_five_people.html.erb
<div class="container-fluid">
  <div class="pull-left">
    <h2 class="text-center remove-margin">Las 5 personas mas facturadas</h2>
  </div>
</div>
<hr>
<div class="pull-left">
  <% @people.each do |p| %>
  <h3> <%= p[0] %> $<%= p[1].round(2) %></h3>
  <% end %>
</div>
<div class="pull-right">
  <%= link_to 'Volver', client_path(@client), class: "btn btn-sm btn-info" %>
</div>