learn-rails/config/routes.rb
Rails.application.routes.draw do

  root 'clients#index'

  resources :clients do
    get '/top_five_people' => 'clients#top_five_people'
    get '/invoices/amount_per_year' => 'invoices#amount_per_year'
    get '/invoices/cont_per_month' => 'invoices#cont_per_month'
    get 'invoices/all' => 'invoices#all'
    resources :invoices, only: [:index, :new, :create, :show, :amount_per_year]
  end
  resources :people
  resources :invoices, only: [:edit, :update, :destroy]
  resources :contacts

end

learn-rails/app/models/invoice.rb
class Invoice < ActiveRecord::Base

  belongs_to :client
  belongs_to :person

  paginates_per 10
  max_paginates_per 50

validates :description,
  presence: true,
  length: { maximum: 200 }
validates :amount,
  presence: true,
  numericality: {
    greater_than: 0,
    less_than_or_equal_to: 1000000000
  }
validates :date_issue,
  presence: true
validates :client_id,
  presence: true
validates :person_id,
  presence: true


end

learn-rails/app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  def index

    @client = Client.find(params[:client_id])

    if ( params['year'] == "" || params['year'] == "all" )
      @invoices = @client.invoices.order("date_issue DESC").page params[:page]
      params['year'] = "all"
    else
      @year = params['year'] || Time.new.year
      @t1 = Time.new(@year)
      @t2 = Time.new((@year.to_i + 1).to_s)
      @invoices = @client.invoices.where({date_issue: @t1..@t2}).order("date_issue DESC").page params[:page]
      @count = @client.invoices.where({date_issue: @t1..@t2}).count
    end
  end

  def all
    @client = Client.find(params[:client_id])
  end

  # GET /invoices/1
  def show
    @person = Person.find(@invoice.person_id)
  end

  # GET /invoices/new
  def new
    @client = Client.find(params[:client_id])
    @invoice = Invoice.new
    @people = Person.all
  end

  # GET /invoices/1/edit
  def edit
    @people = Person.all
    @client = Client.find(@invoice.client_id)
  end

  # POST /invoices
  def create
    @client = Client.find(params[:client_id])
    @invoice = @client.invoices.new(invoice_params)

      if @invoice.save
        redirect_to @client, notice: 'La factura ha sido creada.'
      else
        format.html { render :new }
      end
  end

  # PATCH/PUT /invoices/1
  def update
    @client = Client.find(@invoice.client_id)
      if @invoice.update(invoice_params)
        redirect_to client_invoices_path(@client) , notice: 'La factura ha sido actualizada correctamente.'
      else
        format.html { render :edit }
      end
  end

  # DELETE /invoices/1
  def destroy
    @client = Client.find(@invoice.client_id)
    @invoice.destroy
    redirect_to :back, notice: 'La factura ha sido borrada correctamente.'
  end

  def amount_per_year
    @year = params['year'] || Time.new.year
    @t1 = Time.new(@year)
    @t2 = Time.new((@year.to_i + 1).to_s)
    @client = Client.find(params[:client_id])
    @invoices = @client.invoices.where({date_issue: @t1..@t2})
    @total_amount = @invoices.inject(0){ |amount, invoice| amount + invoice.amount }
  end

  def cont_per_month
    @year = params['year'] || Time.new.year
    @t1 = Time.new(@year)
    @t2 = Time.new((@year.to_i + 1).to_s)
    @client = Client.find(params[:client_id])
    @invoices = @client.invoices.where({date_issue: @t1..@t2})

    @meses = ['nada', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo',
              'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
              'Noviembre', 'Diciembre']
    @cont = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    @invoices.each { |iv|
      @cont[iv.date_issue.month] += 1
      # @cont[iv.date_issue.month] += iv.amount.to_f
      # @cont[iv.date_issue.month] = @cont[iv.date_issue.month].round(2)
    }

  end


  private
    # Use callbacks to share common setup or constraints between actions.

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def invoice_params
    params.require(:invoice).permit(:client_id, :person_id, :description, :amount, :date_issue)
  end
end

learn-rails/app/views/invoices/_form.html.erb
<%= form_for( [@client, @client.invoices.build] ) do |f| %>
  <% if @invoice.errors.any? %>
    <div class="container container-fluid">
      <div id="error_explanation">
        <h3> Encontramos <%= pluralize(@invoice.errors.count, "error") %>/es en el formulario:</h3>
        <ul>
        <% @invoice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <fieldset>
  <h3><legend class="text-center"> <%= @title %> </h3></legend>

  <div class="field form-group">
    <%= f.label :"Personería Jurídica", class: "col-md-4 control-label" %><br>
    <%= f.select(:person_id) do  %>
      <% @people.each do |person| -%>
        <%= content_tag(:option, person.name, value: person.id) %>
      <% end %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= f.label :description, class: "col-md-4 control-label" %><br>
    <%= f.text_area :description, class: "form-control", required: "true" %>
  </div>
  <div class="field form-group">
    <%= f.label :Monto, class: "col-md-4 control-label" %><br>
    <%= f.number_field :amount, class: "form-control", in: 1.0..999999.0, step: 0.5, required: "true" %>
  </div>
  <div class="field form-group">
    <%= f.label :"Fecha de emisión", class: "col-md-4 control-label" %><br>
    <%= f.date_field :date_issue, class: "form-control", required: "true" %>
  </div>
  <div class="actions form-group pull-right">
    <%= link_to "Cancelar", client_invoices_path(@client), class:"btn btn-danger" %>
    <%= f.submit class:"btn btn-primary", value: "Guardar"%>
  </div>
<% end %>

learn-rails/app/views/invoices/amount_per_year.html.erb
<div class="container-fluid">
  <div class="pull-left">
    <h2 class="text-center remove-margin">Monto anual</h2>
  </div>
  <div class="pull-right">
    <form class="form-inline" method="GET">
      <div class="form-group">
        <input type="number" class="form-control" name="year" value="" placeholder= <%= @year %>>
        <button class="btn btn-default" type="submit">Filtrar</button>
      </div>
    </form>
  </div>
</div>
<hr>
<div class="pull-left">
  <h3> "En <%= @year %> facturó $ <%= @total_amount %>"</h3>
</div>
<div class="pull-right">
  <%= link_to 'Volver', client_path(@client), class: "btn btn-sm btn-info" %>
</div>

learn-rails/app/views/invoices/cont_per_month.html.erb
<div class="container-fluid">
  <div class="pull-left">
    <h2 class="text-center remove-margin"> Facturas mensuales</h2>
  </div>
  <div class="pull-right">
    <form class="form-inline" method="GET">
      <div class="form-group">
        <input type="number" class="form-control" name="year" value="" placeholder= <%= @year %>>
        <button class="btn btn-default" type="submit">Filtrar</button>
      </div>
    </form>
  </div>
</div>
<hr>

<div class="col-md-8 col-md-offset-0">
  <table class="table table-hover table-bordered table-condensed text-center">
    <thead>
      <tr>
        <th class="text-center"> Mes </th>
        <th class="text-center"> Cantidad </th>
      </tr>
    </thead>
    <tbody>
      <% 1.upto(12) { |index| %>
        <tr>
          <td> <%= @meses[index] %> </td>
          <td> <%= @cont[index] %> </td>
        </tr>
      <% } %>
    </tbody>
  </table>
  <div class="pull-right">
    <%= link_to 'Volver', client_path(@client), class: "btn btn-sm btn-info" %>
  </div>
</div>

learn-rails/app/views/invoices/edit.html.erb
			<div class="panel panel-default">
				<div class="panel-body">

					<div class="hidden">
						<%= @title = "Edición de factura" %>
					</div>


					<%= form_for( @invoice ) do |f| %>
					  <% if @invoice.errors.any? %>
					    <div class="container container-fluid">
					      <div id="error_explanation">
					        <h3> Encontramos <%= pluralize(@invoice.errors.count, "error") %>/es en el formulario:</h3>
					        <ul>
					        <% @invoice.errors.full_messages.each do |msg| %>
					          <li><%= msg %></li>
					        <% end %>
					        </ul>
					      </div>
					    </div>
					  <% end %>
					  <fieldset>
					  <h3><legend class="text-center"> <%= @title %> </h3></legend>

					  <div class="field form-group">
					    <%= f.label :"Personería Jurídica", class: "col-md-4 control-label" %><br>
					    <!-- <%= f.number_field :person_id, class: "form-control", required: "true" %> -->
					    <%= f.select(:person_id) do  %>
					      <% @people.each do |person| -%>
					        <%= content_tag(:option, person.name, value: person.id) %>
					      <% end %>
					    <% end %>
					  </div>
					  <div class="field form-group">
					    <%= f.label :description, class: "col-md-4 control-label" %><br>
					    <%= f.text_area :description, class: "form-control", required: "true" %>
					  </div>
					  <div class="field form-group">
					    <%= f.label :Monto, class: "col-md-4 control-label" %><br>
					    <%= f.number_field :amount, class: "form-control", in: 1.0..999999.0, step: 0.5, required: "true" %>
					  </div>
					  <div class="field form-group">
					    <%= f.label :"Fecha de emisión", class: "col-md-4 control-label" %><br>
					    <%= f.date_field :date_issue, class: "form-control", required: "true" %>
					  </div>
					  <div class="actions form-group pull-right">
					    <%= link_to "Volver", client_invoices_path(@invoice.client) , class:"btn btn-danger" %>
					    <%= f.submit class:"btn btn-primary", value: "Guardar"%>
					  </div>
					<% end %>


				</div>
			</div>
		</div>
	</div>
</div>

learn-rails/app/views/invoices/index.html.erb
      <%= render template: 'notice' %>
        <div class="container-fluid">
          <div class="pull-left">
            <h2 class="text-center remove-margin">
              Facturas de <%= @client.firstname %> <%= @client.lastname %>
            </h2>
          </div>
          <div class="pull-right">
            <form class="form-inline" method="GET">
              <div class="form-group">
                <input type="number" class="form-control" min="1900" name="year" value="" placeholder= <%= @year %> >
                <button class="btn btn-default" type="submit">Filtrar</button>
              </div>
            </form>
          </div>
        </div>
        <hr>
        <div class="container-fluid">
          <div class="pull-left">
            <% if @count %>
              <h4>Cantidad total de facturas: <%= @count %> - Año: <%= @year %> </h4>
            <% else %>
              <h4> Todas las facturas </h4>
            <% end %>
          </div>
        </div>

        <table class="table table-hover table-bordered table-condensed text-center">
        <thead>
          <tr>
            <th class="text-center" >Personeria Juridica</th>
            <th class="text-center" >Descripción</th>
            <th class="text-center" >Monto</th>
            <th class="text-center" >Fecha de emisión</th>
            <th class="text-center" >Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.person.name %></td>
            <td><%= invoice.description %></td>
            <td>$<%= invoice.amount %></td>
            <td><%= invoice.date_issue.strftime "%d-%m-%Y" %></td>
            <td><%= link_to 'Ver', "invoices/#{invoice.id}", class:"btn btn-sm btn-info" %>
              <%= link_to 'Editar', edit_invoice_path(invoice), class:"btn btn-sm btn-info" %>
              <%= link_to 'Eliminar', invoice, class:"btn btn-sm btn-danger",
              method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="pull-left">
          <%= paginate @invoices %>
        </div>
        <div class="pull-right">
          <%= link_to 'Crear factura nueva', new_client_invoice_path, class:"btn btn-default" %>
          <%= link_to 'Volver', client_path(@client), class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>

learn-rails/app/views/invoices/new.html.erb
			<div class="panel panel-default">
				<div class="panel-body">

					<div class="hidden">
						<%= @title = "Crear factura" %>
					</div>
					<%= render 'form' %>

				</div>
			</div>
		</div>
	</div>
</div>

learn-rails/app/views/invoices/show.html.erb
<div class="col-md-9 col-md-offset-0">
	<div class="panel panel-default">
		<div class="panel-body">

			<div class="text-center" >
			  <h3><legend class="text-center"> Informaci&oacute;n de la factura </h3></legend>

				<%= render template: 'notice' %>

        <h5>
          <strong>Cliente:</strong>
          <%= @invoice.client.firstname %> <%= @invoice.client.lastname %>
        </h5>

        <h5>
          <strong>Persona juridica:</strong>
          <%= @person.name %>
        </h5>

        <h5>
          <strong>Descripción:</strong>
          <%= @invoice.description %>
        </h5>

        <h5>
          <strong>Monto:</strong>
          $ <%= @invoice.amount %>
        </h5>

        <h5>
          <strong>Fecha de emisión:</strong>
          <%= @invoice.date_issue.strftime "%d-%m-%Y" %>
        </h5>
      </div>
    </div>
  </div>
	<div class="pull-left">
	  <%= link_to 'Editar', edit_invoice_path(@invoice), class: "btn btn-sm btn-info" %>
	</div>
	<div class="pull-right">
	  <%= link_to 'Volver', :back, class: "btn btn-sm btn-default" %>
	</div>
</div>